In [1]:
import numpy as np
import sqlite3

con = sqlite3.connect('../../instance/recommend_system.sqlite')
db_env = con.cursor()

In [5]:
db_env.execute('SELECT user_id, post_id FROM YOU_LIKE')
users_like_items = db_env.fetchall()
print(users_like_items)

[(20, 9), (20, 20), (20, 11), (20, 12), (20, 13), (10, 3863), (10, 692), (10, 786), (10, 2906), (10, 5413), (10, 741), (10, 3205), (10, 5543), (10, 3345), (22, 3225), (22, 977), (22, 5606), (22, 1363), (22, 1226), (23, 6654), (23, 3062), (23, 1701), (23, 1712), (23, 431), (23, 402), (23, 2672), (23, 2822), (24, 2740), (24, 5623), (24, 3304), (24, 894), (24, 3844), (24, 1538), (25, 1458), (25, 3286), (25, 5643), (25, 5500), (25, 4772), (25, 64), (25, 1099), (25, 3384), (26, 4143), (26, 1948), (26, 782), (26, 2804), (26, 2270), (26, 2760), (27, 6060), (27, 4002), (27, 6192), (27, 3937), (27, 3907), (27, 4946), (27, 309), (27, 2532)]


In [22]:
users_id = list(set([rec[0] for rec in users_like_items]))
posts_id = list(set([rec[1] for rec in users_like_items]))
# users_id.sort()
# posts_id.sort()
print('unique users_id: ', users_id)
print('unique posts_id: ', posts_id)

unique users_id:  [10, 20, 22, 23, 24, 25, 26, 27]
unique posts_id:  [1538, 3844, 3205, 2822, 9, 11, 12, 13, 5643, 782, 3345, 786, 402, 20, 894, 3863, 3225, 1948, 4002, 4772, 5413, 1701, 5543, 6060, 431, 1712, 4143, 1458, 6192, 692, 2740, 309, 3384, 64, 3907, 2760, 1226, 1099, 977, 4946, 1363, 3286, 2906, 2270, 3937, 2532, 741, 5606, 3304, 2672, 2804, 3062, 5623, 5500, 6654]


In [25]:
rows_user_matrix = {}
for user_id in users_id:
  rows_user_matrix[user_id] = []
  for post_id in posts_id:
    if (user_id, post_id) in users_like_items:
      rows_user_matrix[user_id].append(1)
    else:
      rows_user_matrix[user_id].append(0)

rows_user_matrix

{10: [0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 20: [0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 22: [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 23: [0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
 

In [30]:
list(rows_user_matrix.keys())[0]

[10, 20, 22, 23, 24, 25, 26, 27]

In [26]:
matrix_users_like_items = np.array([rows_user_matrix[user_id] for user_id in users_id])
print(matrix_users_like_items)

[[0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0
  0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1
  0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 0
  0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]]


In [48]:
np.corrcoef(matrix_users_like_items)

array([[ 1.        , -0.13987572, -0.13987572, -0.18248972, -0.15478181,
        -0.18248972, -0.15478181, -0.18248972],
       [-0.13987572,  1.        , -0.1       , -0.13046561, -0.11065667,
        -0.13046561, -0.11065667, -0.13046561],
       [-0.13987572, -0.1       ,  1.        , -0.13046561, -0.11065667,
        -0.13046561, -0.11065667, -0.13046561],
       [-0.18248972, -0.13046561, -0.13046561,  1.        , -0.1443689 ,
        -0.17021277, -0.1443689 , -0.17021277],
       [-0.15478181, -0.11065667, -0.11065667, -0.1443689 ,  1.        ,
        -0.1443689 , -0.12244898, -0.1443689 ],
       [-0.18248972, -0.13046561, -0.13046561, -0.17021277, -0.1443689 ,
         1.        , -0.1443689 , -0.17021277],
       [-0.15478181, -0.11065667, -0.11065667, -0.1443689 , -0.12244898,
        -0.1443689 ,  1.        , -0.1443689 ],
       [-0.18248972, -0.13046561, -0.13046561, -0.17021277, -0.1443689 ,
        -0.17021277, -0.1443689 ,  1.        ]])

In [49]:
_[:, 1]

array([-0.13987572,  1.        , -0.1       , -0.13046561, -0.11065667,
       -0.13046561, -0.11065667, -0.13046561])

In [47]:
np.argsort(_)[:4]

array([0, 7, 3, 5], dtype=int64)

In [35]:
users_id.index(20)

1